// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite
RWTexture2D<float4> Result;
RWTexture2D<float4> FireMap;

Texture2D HeightMap;

float floodLevel; // flood level scaled from 0-1 based on mapheight



[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{


    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
